base_url = "https://blog.rengaonline.in"
title = "Renga's Learning"
description = "Blog to add my leaning on tech contents"
default_language = "en"
# theme = ""  # set this to a theme name once you add one under themes/

compile_sass = true
minify_html = false
generate_feeds = true
feed_filenames = ["atom.xml"]

taxonomies = [
    {name = "tags", feed = true},
    {name = "categories", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
author = "Renganatha"
